

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:  
    runs-on: windows-latest
    
    steps:
      - name: Set the value
        # shell: pwsh
        id: step_one
        run: |
          powershell $Service = Get-Date -Format "dd/MM/yyyy HH:mm:ss" 
          powershell write-Output("$Service - Not Running correct number of count")
