

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:  
    runs-on: windows-latest
    
    steps:
      - name: Set the value
        shell: pwsh
        id: step_one
        run: |
          $Service = Get-Date -Format "dd/MM/yyyy HH:mm:ss" 
          echo '::set-output name=SELECTED_COLOR::$Service'
          
      - name: Set the value1
        run: |
          echo "The selected color is ${{ steps.step_one.SELECTED_COLOR }}" 
