

name: Test

on:
  push:
    branches: [ "main" ]

jobs:
 


  build:
  
    runs-on: windows-2019
    env:
        ReleaseRepoName: Build_Releases_Mobility

    steps:

      - name: Set the value
        id: step_one
        run: |
          echo "yellow"
          
      - name: Use the value
        id: step_two
        run: |
          echo $Test
        env:
          Test: ${{ env.ReleaseRepoName }}
          Test2: ${{ steps.step_one }}
