

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
    
      - name: Set color
        id: version
        run: |
          echo "builddate=Test" >> $GITHUB_ENV
          
      - name: Test with environment variables
        run: |
          echo $DEBUG
          $DEBUG
        env:
          DEBUG: ${{ steps.version.outputs.builddate }}-DEBUG
