

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
       
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
    - name: Echo current date
      run: echo $NOW # Gives "2022-12-11T01:42:20"
      
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV      

        
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
        
    - name: Set the value1
      id: step_one1
      run: |
        echo "action_state1=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        
    - name: Use the value1
      id: step_two1
      run: |
        echo "${{ env.action_state1 }}" # This will output 'yellow'
