

name: Test

on:
  push:
    branches: [ "main" ]

jobs:
 


  build:
  
    runs-on: windows-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Test with environment variables
        run: echo $TAG_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
