

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Get-Current-Date
        # id: step_one
        run: |
          echo "action_state=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT      
    outputs:
      DateTime: ${{steps.step_one.outputs.action_state}}

  build2:  
    runs-on: windows-2019
    needs: build
    steps:
      - name: Set the value
        run: |
          echo ${{needs.build.outputs.DateTime}}
