

name: Test

on:
  push:
    branches: [ "main" ]

jobs:
 


  build:
  
    runs-on: windows-latest
    steps:
    
    - name: Set output
      id: stepid
      run: echo "::set-output name=count::5"
      
    - name: Oldway
      run: echo "The count was ${{ steps.stepid.outputs.count }}"
      
    - name: Set output1
      id: stepid1
      run: echo "count=5" >> $GITHUB_OUTPUT
      
    - name: New Way
      run: echo "The count was ${{ steps.stepid1.outputs.count }}"
