

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
          
      - name: Outputs
        id: Outputs
        run: |
          echo $Test
          echo $Test1
        env:
            Test: ${{steps.step_one.outputs.action_state}}
            Test1: ${{steps.step_one.outputs.SELECTED_COLOR}}
