

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_OUTPUT
          echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT       
    outputs:
      Test: ${{steps.step_one.outputs.action_state}}
      Test1: ${{steps.step_one.outputs.SELECTED_COLOR}}
      
      # - name: Output Data
       #  id: outputs
       #  run: |
       #  env:
          # Test: ${{steps.step_one.outputs.action_state}}
          # Test1: ${{steps.step_one.outputs.SELECTED_COLOR}}

  build2:  
    runs-on: windows-2019
    needs: build
    steps:
      - name: Set the value
        run: |
          echo ${{needs.build.outputs.Test}}
