

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
    
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
      
      - name: Get current date
        id: date
        run: |
          # echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
          # echo "::set-output name={name}::{value}"
          echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
        
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Test with input
        run: |
          echo "Mona-the-Octocat-${{ steps.date.outputs.date }}"
          echo "${{ steps.date.outputs.date }}"
          echo "${{ steps.date.outputs.date }}"
          echo "$GITHUB_OUTPUT"
          echo "$date"
          echo "${{ env.date }}"
