

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Get-Current-Date
        id: getdate
        run: |
          echo "currentdate=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT      
    outputs:
      DateTime: ${{steps.getdate.outputs.currentdate}}

  build2:  
    runs-on: windows-2019
    needs: build
    steps:
      - name: Set the value
        run: |
          echo ${{needs.build.outputs.DateTime}}
