

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
    
      - name: Set color
        id: getdate
        shell: pwsh
        run: |
          Get-Date -Format "dd/MM/yyyy HH:mm:ss"
          
      - name: Test with environment variables
        run: |
          echo $TAG_NAME
          $TAG_NAME
        env:
          TAG_NAME: nightly-tag-${{ env.getdate }}
