

name: Test

on:
  push:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: windows-2019  # For a list of available runner types, refer to

    steps:
          
      - name: Set the value
        id: step_one
        run: |
          # echo "action_state=yellow" >> $GITHUB_ENV
          echo "action_state=yellow"
          
      - name: Use the value
        id: step_two
        run: |
          echo $Test
          echo "$Test"
        env:
          Test: "${{ steps.step_one.action_state }}"
